stages:
  - build

before_script:
  - docker-compose up -d

build:
  stage: build
  image: cje172/ride-or-not:hanium
  script:
    - echo "sdk.dir=$ANDROID_HOME" >> local.properties
    - echo "BASE_URL=$BASE_URL" >> local.properties
    - echo "NAVER_MAP=$NAVER_MAP" >> local.properties
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

cache:
  paths:
    - /cache