stages:
  - build

build:
  stage: build
  image: cje172/ride-or-not:hanium
  script:
    - echo "sdk.dir=$ANDROID_HOME" >> ./app/local.properties
    - echo "BASE_URL=$BASE_URL" >> ./app/local.properties
    - echo "NAVER_MAP=$NAVER_MAP" >> ./app/local.properties
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

cache:
  paths:
    - /cache